on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: futcommercialacr.azurecr.io
        username: ${{ secrets.acr_futcommercialacr_username }}
        password: ${{ secrets.acr_futcommercialacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t futcommercialacr.azurecr.io/futcommercialdevaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push futcommercialacr.azurecr.io/futcommercialdevaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_futcommercialdevaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep msdemoapp212321 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace msdemoapp212321`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: msdemoapp212321
        container-registry-url: futcommercialacr.azurecr.io
        container-registry-username: ${{ secrets.acr_futcommercialacr_username }}
        container-registry-password: ${{ secrets.acr_futcommercialacr_password }}
        secret-name: futcommerciadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: msdemoapp212321
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          futcommercialacr.azurecr.io/futcommercialdevaks:${{ github.sha }}
        imagepullsecrets: |
          futcommerciadockerauth
